(() => {
  "use strict";
  const API_URL = "api/index.php";
  const $ = id => document.getElementById(id);
  let busy=false, customerBusy=false, customerPage=1, customerSearch="", customerTotalPages=1;
  const setText=(id,v)=>{const e=$(id);if(e)e.textContent=v??""};
  const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
  const showLoading=(show,text)=>{const e=$("loading");if(!e)return;e.classList.toggle("hidden",!show);const s=e.querySelector("span");if(s&&text)s.textContent=text};
  const setError=m=>{if($("error"))$("error").textContent=m||""};
  async function api(action,options={}){const o={method:options.method||"GET",credentials:"same-origin",headers:{Accept:"application/json"}};if(options.body!==undefined){o.headers["Content-Type"]="application/json";o.body=JSON.stringify(options.body)}const r=await fetch(`${API_URL}?action=${encodeURIComponent(action)}`,o);let d;try{d=await r.json()}catch(e){throw new Error(`Server returned HTTP ${r.status}.`)}if(!r.ok||!d||d.success!==true)throw new Error(d?.message||`Request failed (HTTP ${r.status}).`);return d}

  $("toggle")?.addEventListener("click",()=>{const i=$("password"),b=$("toggle"),v=i.type==="text";i.type=v?"password":"text";b.textContent=v?"Show":"Hide"});
  $("loginForm")?.addEventListener("submit",async e=>{e.preventDefault();if(busy)return;const username=$("email").value.trim(),password=$("password").value;setError("");if(!username||!password){setError("Please enter username and password.");return}busy=true;$("login").disabled=true;$("login").textContent="Signing In...";try{const r=await api("login",{method:"POST",body:{username,password}});sessionStorage.setItem("sp_tinted_user",JSON.stringify(r.user));showDashboard(r.user);await loadDashboard()}catch(err){setError(err.message)}finally{busy=false;$("login").disabled=false;$("login").textContent="Sign In"}});

  function showDashboard(user){$("loginScreen")?.classList.add("hidden");$("app")?.classList.remove("hidden");setText("pname",user?.fullName||user?.name||"Admin");setText("prole",user?.role||"User");setText("avatar",(user?.fullName||"A").charAt(0).toUpperCase())}
  async function checkSession(){try{const r=await api("session");if(r.user){sessionStorage.setItem("sp_tinted_user",JSON.stringify(r.user));showDashboard(r.user);await loadDashboard()}}catch(e){sessionStorage.removeItem("sp_tinted_user")}}
  async function loadDashboard(){showLoading(true,"Loading Dashboard...");try{const r=await api("dashboard"),d=r.data||{};setText("totalCustomers",d.totalCustomers||0);setText("todayRegistration",d.todayRegistration||0);setText("totalVehicles",d.totalVehicles||0);setText("monthlyRegistration",d.monthlyRegistration||0);const rows=d.recent||[],t=$("recent");if(t)t.innerHTML=rows.length?rows.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.name)}</td><td>${esc(x.vehicle)}</td><td>${esc(x.phone)}</td><td>${esc(x.date)}</td></tr>`).join(""):"<tr><td colspan=\"5\">No customers found.</td></tr>"}catch(e){console.error(e);setError(e.message)}finally{showLoading(false)}}

  function setActive(page){["navDashboard","navCustomer"].forEach(id=>$(id)?.classList.remove("active"));$(page==="customer"?"navCustomer":"navDashboard")?.classList.add("active");$("dashboardPage")?.classList.toggle("hidden",page!=="dashboard");$("customerPage")?.classList.toggle("hidden",page!=="customer");setText("pageTitle",page==="customer"?"Customer":"Dashboard")}
  $("navDashboard")?.addEventListener("click",()=>setActive("dashboard"));
  $("navCustomer")?.addEventListener("click",()=>{setActive("customer");loadCustomers(1)});
  $("refresh")?.addEventListener("click",()=>$("customerPage")?.classList.contains("hidden")?loadDashboard():loadCustomers(customerPage));
  $("customerRefresh")?.addEventListener("click",()=>loadCustomers(customerPage));
  $("customerSearchBtn")?.addEventListener("click",()=>{customerSearch=$("customerSearch").value.trim();loadCustomers(1)});
  $("customerSearch")?.addEventListener("keydown",e=>{if(e.key==="Enter"){customerSearch=e.target.value.trim();loadCustomers(1)}});
  $("customerPrev")?.addEventListener("click",()=>{if(customerPage>1)loadCustomers(customerPage-1)});
  $("customerNext")?.addEventListener("click",()=>{if(customerPage<customerTotalPages)loadCustomers(customerPage+1)});

  async function loadCustomers(page=1){if(customerBusy)return;customerBusy=true;customerPage=page;setText("customerResultInfo","Loading...");const body={page,perPage:20,search:customerSearch};try{const r=await api("customer_dashboard",{method:"POST",body}),d=r.data||{},s=d.stats||{},pg=d.pagination||{};setText("customerTotal",s.total||0);setText("customerNew",s.new||0);setText("customerReturning",s.returning||0);setText("customerVisits",s.visits||0);customerTotalPages=Number(pg.totalPages)||1;setText("customerPageInfo",`Page ${pg.page||1} of ${customerTotalPages}`);setText("customerResultInfo",`${pg.total||0} customer records`);const rows=d.customers||[],t=$("customerRows");if(!t)return;if(!rows.length){t.innerHTML='<tr><td colspan="9">No customers found.</td></tr>';return}t.innerHTML=rows.map(x=>`<tr><td><b>${esc(x.customerCode)}</b></td><td><b>${esc(x.name)}</b></td><td>${esc(x.phone)}</td><td>${esc(x.vehicle)}</td><td>${esc(x.plate)}</td><td><span class="type-badge ${String(x.type).toLowerCase()==='returning'?'returning':'new'}">${esc(x.type)}</span></td><td>${esc(x.visit)}</td><td>${esc(formatDate(x.registrationDate))}</td><td><button class="view-btn" type="button" data-id="${x.id}">View</button></td></tr>`).join("");t.querySelectorAll(".view-btn").forEach(b=>b.addEventListener("click",()=>viewCustomer(b.dataset.id)))}catch(e){setText("customerResultInfo",e.message);const t=$("customerRows");if(t)t.innerHTML=`<tr><td colspan="9">${esc(e.message)}</td></tr>`}finally{customerBusy=false}}
  function formatDate(v){if(!v)return"";const d=new Date(String(v).replace(" ","T"));if(Number.isNaN(d.getTime()))return v;return d.toLocaleDateString("en-GB")+" "+d.toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"})}
  async function viewCustomer(id){try{const r=await api("customer_by_id",{method:"POST",body:{id}}),d=r.data||{};setText("viewCustomerName",d.customer_name||"Customer");setText("viewCustomerCode",d.customer_code||"");const box=$("customerViewDetails");if(box)box.innerHTML=`<div><span>Phone</span><b>${esc(d.phone_number)}</b></div><div><span>Car Plate</span><b>${esc(d.car_plate)}</b></div><div><span>Vehicle</span><b>${esc(`${d.brand||""} ${d.car_model||""}`.trim())}</b></div><div><span>Customer Type</span><b>${esc(d.customer_type)}</b></div><div><span>Visit</span><b>${esc(d.visit)}</b></div><div><span>Registration</span><b>${esc(formatDate(d.registration_date))}</b></div><div><span>Notes</span><b>${esc(d.notes||"-")}</b></div>`;$("customerViewModal")?.classList.remove("hidden")}catch(e){alert(e.message)}}
  $("closeCustomerView")?.addEventListener("click",()=>$("customerViewModal")?.classList.add("hidden"));$("customerViewModal")?.addEventListener("click",e=>{if(e.target===$("customerViewModal"))$("customerViewModal").classList.add("hidden")});

  const logoutModal=$("logoutModal");function closeLogout(){logoutModal?.classList.add("hidden");document.body.classList.remove("modal-open")}$("logout")?.addEventListener("click",()=>{logoutModal?.classList.remove("hidden");document.body.classList.add("modal-open")});$("closeLogout")?.addEventListener("click",closeLogout);$("cancelLogout")?.addEventListener("click",closeLogout);$("confirmLogout")?.addEventListener("click",async()=>{if(busy)return;busy=true;try{await api("logout",{method:"POST",body:{}})}catch(e){console.error(e)}finally{sessionStorage.removeItem("sp_tinted_user");closeLogout();$("app")?.classList.add("hidden");$("loginScreen")?.classList.remove("hidden");$("password").value="";busy=false}});

  const settingsNav=$("settingsNav"),passwordModal=$("passwordModal");function closePassword(){passwordModal?.classList.add("hidden");document.body.classList.remove("modal-open");$("passwordForm")?.reset();$("passwordError").textContent="";$("passwordSuccess").textContent=""}settingsNav?.addEventListener("click",()=>{passwordModal?.classList.remove("hidden");document.body.classList.add("modal-open")});$("closePassword")?.addEventListener("click",closePassword);$("cancelPassword")?.addEventListener("click",closePassword);document.querySelectorAll(".password-toggle").forEach(b=>b.addEventListener("click",()=>{const i=$(b.dataset.target),v=i.type==="text";i.type=v?"password":"text";b.textContent=v?"Show":"Hide"}));$("passwordForm")?.addEventListener("submit",async e=>{e.preventDefault();const a=$("currentPassword").value,n=$("newPassword").value,c=$("confirmPassword").value;$("passwordError").textContent="";$("passwordSuccess").textContent="";if(n.length<8)return $("passwordError").textContent="New password must be at least 8 characters.";if(n!==c)return $("passwordError").textContent="New password and confirmation do not match.";try{await api("change_password",{method:"POST",body:{currentPassword:a,newPassword:n}});$("passwordSuccess").textContent="Password changed successfully.";setTimeout(closePassword,900)}catch(err){$("passwordError").textContent=err.message}});
  document.addEventListener("keydown",e=>{if(e.key!=="Escape")return;if(!logoutModal?.classList.contains("hidden"))closeLogout();else if(!passwordModal?.classList.contains("hidden"))closePassword();else $("customerViewModal")?.classList.add("hidden")});
  checkSession();
})();
